name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.1
    env:
      GAME: this-is-a-game
      CHANNELS: "win linux web macOS"
      GODOT_VERSION: 4.1
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
          submodules: true
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci

      - run: ./scripts/prepare-template.sh

      - name: Build & Publish
        shell: bash
        env:
          BUTLER_API_KEY: ${{secrets.BUTLER_API_KEY}}
        run: ./scripts/publish.sh $GITHUB_REF_NAME $CHANNELS
